name: Unit Test

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven

    - name: Print Maven info
      run: mvn -version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Tests and verify
      run: mvn --batch-mode --update-snapshots verify

    - name: Report tests
      run: mvn surefire-report:report

    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/target/surefire-reports/**/*.xml'
